name: deploy dockerized web app
on:
  push:
    branches: [ master ]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER: ritik
          IP: 34.123.168.248
          APP_NAME: ${{ github.event.repository.name }}
        run: |
          eval $(ssh-agent)
          echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan $IP > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          rsync -auz ./ $USER@$IP:./$APP_NAME
          ssh $USER@$IP "cd $APP_NAME && \
          sudo docker-compose up --build -d"